---
title: "02-GWAS"
author: "Hae Kyung Im"
date: "2020-10-20"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Learning objectives of the module
Understand the concept, benefits and limitations.
Perform and interpret GWAS

## Reading
Visscher, Peter M., Naomi R. Wray, Qian Zhang, Pamela Sklar, Mark I. McCarthy, Matthew A. Brown, and Jian Yang. 2017. “10 Years of GWAS Discovery: Biology, Function, and Translation.” American Journal of Human Genetics 101 (1): 5–22.

General intro to association (a bit old)
N. M. Laird and C. Lange, The fundamentals of modern statistical genetics. Chapters 7 and 9.

First large scale GWAS
The Wellcome Trust Consortium "Genome-wide association study of 14,000 cases of seven common diseases and 3,000 shared controls" (2007) Nature 447:661-678. 

Claussnitzer, M., Cho, J. H., Collins, R., Cox, N. J., Dermitzakis, E. T., Hurles, M. E., et al. (2020). A brief history of human disease genetics. Nature, 577(7789), 179–189. http://doi.org/10.1038/s41586-019-1879-7

Tam, V., Patel, N., Turcotte, M., Bossé, Y., Paré, G., & Meyre, D. (2019). Benefits and limitations of genome- wide association studies. Nature Reviews Genetics, 1–18. http://doi.org/10.1038/s41576-019-0127-1

## Introduction

```{r}

```

